[package]
name = "concurrentes-fiuba-2025c1"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "convar_basic"
path = "src/convar_basic.rs"

[[bin]]
name = "convar_pingpong"
path = "src/convar_pingpong.rs"

[[bin]]
name = "semaphore"
path = "src/semaphore.rs"

[[bin]]
name = "mutex_queue"
path = "src/mutex_queue.rs"

[[bin]]
name = "monitor"
path = "src/monitor.rs"

[dependencies]
tokio = { version = "1.44.2", features = ["full"] }
